echo "prefix = ctrl + s"
echo ""
echo ""
echo "***** Pane Commands *****"
echo "tmux new-window (prefix + c)"
echo "tmux select-window (prefix + 0-9)"
echo "tmux rename-window (prefix + ,)"
echo "tmux split-window (prefix + %)"
echo "tmux split-window -h (prefix + \)"
echo ""
echo ""

echo "***** Session Commands *****"
echo "tmux commands"
echo "tmux new -s session_name"
echo "tmux attach -t session_name"
echo "tmux switch -t session_name"
echo "tmux list-sessions"
echo "tmux detach (prefix + d)"
echo "tmux rename-session -t 0 session_name"
echo "tmux kill-session -t session_name"
echo "tmux kill-server"
echo "tmux list-keys"
echo "tmux list-commands"
echo ""
echo ""

echo "***** Pane Resizing *****"
echo "tmux resize-pane -U (prefix + ctrl + up)"
echo "tmux resize-pane -D (prefix + ctrl + down)"
echo "tmux resize-pane -L (prefix + ctrl + left)"
echo "tmux resize-pane -R (prefix + ctrl + right)"

